### ISSUE TITLE
Make an upscaled picture log contain the generation parameters

### ISSUE THREAD

**Issue by NovNovikov** [phr00t/stable-diffusion-webui#1]
Can you make the upscaled pictures log keep their original log? For now it just saves the upscaled picture to "extras-images" folder with a number in picture name and a log txt file that only describes the upscale parameters, but it would be great to have full information from the log file of the non-upscaled image.

**Comment by phr00t** [comment]
Isn't the original logfile generated in the txt2img folder, if your settings are configured to generate it? The checkbox that does the automatic upscaling doesn't disable any logging, so the original logs should still be generated.

**Comment by NovNovikov** [comment]
Yes, but I use the upscaled ones and going back to maze of folders in txt2img and looking for the same picture and its log file is a pain.
As a workaround - can it be configured that upscaled pictures would be put to the same folder as original ones?

**Comment by phr00t** [comment]
I use the "run_extras" function to generate the upscaled (and face fixed) images, which I don't want to modify (since every modification I make complicates merging with the rapidly developed base repo).

You can change the "extras" output directory in Settings (see "Output directory for images from extras tab"). You can make that point to the same txt2img folder.

**Comment by NovNovikov** [comment]
>You can make that point to the same txt2img folder.

It will just drop all upscaled files into one folder regardsless of prompts, while the originals are inside folders with [seed-prompts] in the folders names. if it just could save it to the same folder where the original was in the firdt place and/or preserve the original name of the picture - that would simplify things a lot.

**Comment by phr00t** [comment]
Sorry, but I don't think this justifies further distancing this fork from the base repo. The log file does get created, and you can make it go into the same folder. If you want to maintain this change yourself for extra simplification, please fork my repo.
