### ISSUE TITLE
The "Face Fix & Upscale" button doesn't take parameters from "Extras", instead always using the same parameters

### ISSUE THREAD

**Issue by NovNovikov** [phr00t/stable-diffusion-webui#2]
Whenever i try to use the upscale function - it doesn't take parameters from "Extras", instead always using the same parameters.
In my case it always takes "Real-ESRGAN General WDN x4x3" and upscale = 2, regardsless of what I selected in the "Extras" tab.

Looks like it uses the parameters from "processing.py" from the line
"modules.extras.run_extras(0, image, None,                   0.0,                   0.0,               0.0,                2,                 3,                 0,                          0.0)"
When I change them directly in the line - it works.

**Comment by phr00t** [comment]
Yeah, this is a known thing. I'm not sure how to get those values from the other tab, so I just went with some values that were acceptable for me. I suggest just editing the processing.py file, as you did, in the meantime. One downside to taking from "extras" are... those are not saved, and require you to tweak them on the "extras" tab every startup... so I personally prefer to just setting it in the processing.py file...
